# audio_dic = {0:"deer",
# 1:"car_horn",
# 2:"lion",
# 3:"deer",
# 4:"wolf",
# 5:"rhino",
# 6:"bear",
# 7:"leopard",
# 8:"bear",
# 9:"spinny_babbler",
# 10:"zebra",
# 11:"hippo",
# 12:"tiger",
# 13:"tiger",
# 14:"wolf",
# 15:"cow",
# 16:"horse",
# 17:"sheep",
# 18:"goat",
# 19:"dog",
# 20:"cat",
# 21:"human"}
audio_dic = {
    0: 'bear',
    1: 'cheetah',
    2: 'elephant',
    3: 'tiger',
}